jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      entries:
      - user:
          name: "admin"
          permissions:
          - "Agent/Build"
          - "Agent/Configure"
          - "Agent/Connect"
          - "Agent/Create"
          - "Agent/Delete"
          - "Agent/Disconnect"
          - "Credentials/Create"
          - "Credentials/Delete"
          - "Credentials/ManageDomains"
          - "Credentials/Update"
          - "Credentials/View"
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Configure"
          - "Job/Create"
          - "Job/Delete"
          - "Job/Discover"
          - "Job/Move"
          - "Job/Read"
          - "Job/Workspace"
          - "Lockable Resources/Reserve"
          - "Lockable Resources/Steal"
          - "Lockable Resources/Unlock"
          - "Lockable Resources/View"
          - "Overall/Administer"
          - "Overall/Read"
          - "Run/Delete"
          - "Run/Replay"
          - "Run/Update"
          - "SCM/Tag"
          - "View/Configure"
          - "View/Create"
          - "View/Delete"
          - "View/Read"
      - user:
          name: "panda"
          permissions:
          - "Overall/Administer"